<?php

/**
 * @file
 * Contains marketo_ma_user.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\marketo_ma_user\Form\MarketoMaUserSettings;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function marketo_ma_user_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the marketo_ma_user module.
    case 'help.page.marketo_ma_user':
      return t('<h3>:title</h3><p>:description</p>', [
        ':title' => 'About',
        ':description' => 'Integrates Marketo with core User actions.',
      ]);

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function marketo_ma_user_form_marketo_ma_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  // @var \Drupal\marketo_ma_user\Form\MarketoMaUserSettings $user_settings_form_class
  $user_settings_form_class = \Drupal::service('class_resolver')->getInstanceFromDefinition(MarketoMaUserSettings::class);
  // Get the marketo user settings form additions.
  $form = $user_settings_form_class->buildForm($form, $form_state);
}

/**
 * Implements hook_user_login().
 */
function marketo_ma_user_user_login($account) {
  // Hand off to the marketo_ma.user service.
  \Drupal::service('marketo_ma.user')->userLogin($account);
}

/**
 * Implements hook_ENTITY_TYPE_create().
 */
function marketo_ma_user_user_create(EntityInterface $entity) {
  // Hand off to the marketo_ma.user service.
  \Drupal::service('marketo_ma.user')->userCreate($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function marketo_ma_user_user_update(EntityInterface $entity) {
  // Hand off to the marketo_ma.user service.
  \Drupal::service('marketo_ma.user')->userUpdate($entity);
}
