<?php
/**
 * @file
 * Contains marketo_ma.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function marketo_ma_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the marketo_ma module.
    case 'help.page.marketo_ma':
      return t('<h3>:about</h3><p>:description</p>', [
        ':about' => 'About',
        ':description' => 'Integration with Marketo marketing automation software.',
      ]);

    default:
  }
}

/**
 * Implements hook_page_attachments().
 *
 * Adds teh marketo ma javascript to all pages.
 */
function marketo_ma_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'marketo_ma/marketo-ma';
}

/**
 * Implements hook_preprocess_page().
 */
function marketo_ma_preprocess_page(&$variables) {
  // Hand off to the marketo_ma service.
  \Drupal::service('marketo_ma')->preProcessPage($variables);
}
