<?php

define('MARKETO_PAGES', "admin\nadmin/*\nbatch\nnode/add*\nnode/*/*\nuser/*/*");
define('MARKETO_WEBFORM_FIELD_DEFAULTS', "FirstName\tFirst Name\nLastName\tLast Name\nEmail\tEmail Address");

define('MARKETO_SCHEMA_WEBFORM', 'marketo_webform');
define('MARKETO_WEBFORM_FIELD_ACTIVE', 'is_active');

define('MARKETO_SCHEMA_WEBFORM_COMPONENT', 'marketo_webform_component');
define('MARKETO_WEBFORM_COMPONENT_KEY', 'marketo_key');
