webform.handler.marketo_ma:
  type: mapping
  label: 'Action'
  mapping:
    marketo_ma_mapping:
      label: 'Webform fields to Marketo fields mapping'
      type: sequence
      sequence:
        type: string
