<?php

/**
 * @file
 * Contains mma_contact.module..
 */

use Drupal\contact\ContactFormInterface;
use Drupal\contact\MessageInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\mma_contact\Hooks\ContactMessageInsert;

/**
 * Implements hook_help().
 */
function mma_contact_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mma_contact module.
    case 'help.page.mma_contact':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integrates Marketo MA with Contact module forms.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_operation().
 */
function mma_contact_entity_operation(EntityInterface $entity) {
  $operations = [];
  if ($entity instanceof ContactFormInterface) {
    $operations['mma_contact_mapping'] = [
      'title' => t('Marketo mapping'),
      'url' => Url::fromRoute('mma_contact.contact.configuration', ['contact_form' => $entity->id()]),
      'weight' => 50,
    ];
  }

  return $operations;
}

/**
 * Implements hook_contact_message_insert().
 */
function mma_contact_contact_message_insert(MessageInterface $message) {
  /** @var \Drupal\Core\DependencyInjection\ClassResolverInterface $class_resolver */
  $class_resolver = \Drupal::service('class_resolver');
  $hook = $class_resolver->getInstanceFromDefinition(ContactMessageInsert::class);
  $hook->contactMessageInsert($message);
}
