<?php

/**
 * @file
 * Drupal Module: Marketo User
 */

/**
 * Implements hook_user_insert().
 */
function marketo_user_user_insert(&$edit, $account, $category) {
  $x = TRUE;
  $data = array(
    'Email' => $edit['mail']
  );
  marketo_prepare_data($data);
}

/**
 * Implements hook_user_update().
 */
function marketo_user_user_update(&$edit, $account, $category) {
  $x = TRUE;
  $data = array(
    'Email' => $edit['mail']
  );
  marketo_prepare_data($data);
}
